spring:
  datasource:
    url: jdbc:mysql://localhost/stfx?useUnicode=true&characterEncoding=utf-8
    username: stfx
    password: Stfx!234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 3

  redis:
    host: localhost
    port: 6379
    database: 51
    timeout: 500
    jedis:
      pool:
        max-idle: 1
        max-active: 5

logging:
  level:
    org.framework: DEBUG
    com.mobaas.stfx: DEBUG