spring:
   datasource:
      url: jdbc:mysql://localhost/stfx?useUnicode=true&characterEncoding=utf-8
      username: stfx
      password: Stfx!234
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 3

mybatis:
   type-aliases-package: com.mobaas.stfx.entity
   mapper-locations: classpath*:mapper/*.xml
  
app:
   schedule:
      enable: true
      dispatch-cron: 0 0/1 * * * ?
      
logging:
  level:
    org.framework: DEBUG
    com.mobaas.stfx: DEBUG